export const HELP_INFORMATION_NEW_SIMULATIONS = 'helpInformationCompartmental.newSimulation'

export const HELP_INFORMATION_CHOOSE_SIMULATIONS = 'helpInformationCompartmental.chooseSimulation'

export const HELP_INFORMATION_OPTIMIZE_PARAMETERS_SIMULATIONS = 'helpInformationCompartmental.optimizeParameters'

export const HELP_INFORMATION_CONFIGURE_PARAMETERS_SIMULATIONS = 'helpInformationCompartmental.configureParameters'  

export const HELP_INFORMATION_CONFIGURE_STATE_VARIANLES_SIMULATIONS = 'helpInformationCompartmental.stateVariables'

export const HELP_INFORMATION_UPLOAD_DATA_SIMULATIONS = 'helpInformationCompartmental.uploadData'

export const HELP_INFORMATION_CHOOSE_DATE_SIMULATIONS = 'helpInformationCompartmental.setDates'

export const HELP_INFORMATION_REVIEW_CONFIGURATION_MESSAGE_SIMULATIONS = 'helpInformationCompartmental.simulationExecuted'

export const HELP_INFORMATION_REVIEW_CONFIGURATION_INFORMATION_SIMULATIONS = 'helpInformationCompartmental.reviewConfiguration'

export const HELP_INFORMATION_FIXED_PARAMETERS_SIMULATIONS = 'helpInformationCompartmental.fixedParameters'

export const HELP_INFORMATION_AGE_MODELS = 'HELP_INFORMATION_AGE_MODELS'

export const HELP_INFORMATION_MOBILITY_MODELS = 'HELP_INFORMATION_MOBILITY_MODELS'