export const AGENTS_MODEL_LOADING = 'AGENTS_MODEL_LOADING'

export const AGENTS_MODEL_REGISTER_ERROR = 'AGENTS_MODEL_REGISTER_ERROR'
export const AGENTS_MODEL_REGISTER_SUCCESS = 'AGENTS_MODEL_REGISTER_SUCCESS'


export const AGENTS_AGE_MODEL_GET_INFORMATION_ERROR = 'AGENTS_AGE_MODEL_GET_INFORMATION_ERROR'
export const AGENTS_AGE_MODEL_GET_INFORMATION_SUCCESS = 'AGENTS_AGE_MODEL_GET_INFORMATION_SUCCESS'




