export const AGENTS_MODEL_LOADING = 'AGENTS_MODEL_LOADING'

export const AGENTS_MODEL_REGISTER_ERROR = 'AGENTS_MODEL_REGISTER_ERROR'
export const AGENTS_MODEL_REGISTER_SUCCESS = 'AGENTS_MODEL_REGISTER_SUCCESS'




