export const DISTRIBUTION_SET_LIST = 'DISTRIBUTION_SET_LIST'
export const DISTRIBUTION_PARAMETERS_SET_LIST = 'DISTRIBUTION_PARAMETERS_SET_LIST'
export const DISTRIBUTION_LOADING = 'DISTRIBUTION_LOADING'
export const DISTRIBUTION_ERROR = 'DISTRIBUTION_ERROR'