export const VALIDATION_QR_LOADING= 'VALIDATION_QR_LOADING'
export const VALIDATION_QR_SUCCESS = 'VALIDATION_QR_SUCCESS'
export const VALIDATION_QR_ERROR= 'VALIDATION_QR_ERROR'


export const QR_ACCOUNT_RECOVERY_LOADING = 'QR_ACCOUNT_RECOVERY_LOADING'
export const QR_ACCOUNT_RECOVERY_SUCCESS = 'QR_ACCOUNT_RECOVERY_SUCCESS'
export const QR_ACCOUNT_RECOVERY_ERROR = 'QR_ACCOUNT_RECOVERY_ERROR'


export const QR_ACCOUNT_SECURITY_QUESTIONS_LOADING = 'QR_ACCOUNT_SECURITY_QUESTIONS_LOADING'
export const QR_ACCOUNT_SECURITY_QUESTIONS_SUCCESS = 'QR_ACCOUNT_SECURITY_QUESTIONS_SUCCESS'
export const QR_ACCOUNT_SECURITY_QUESTIONS_ERROR = 'QR_ACCOUNT_SECURITY_QUESTIONS_ERROR'