export const QUARANTINE_GROUPS_LOADING= 'QUARANTINE_GROUPS_LOADING'
export const QUARANTINE_GROUPS_ERROR = 'QUARANTINE_GROUPS_ERROR'
export const QUARANTINE_GROUPS_SAVE= 'QUARANTINE_GROUPS_SAVE'
export const QUARANTINE_TRACING= 'QUARANTINE_TRACING'

