export const USER_DATA_SUCCESS='USER_DATA_SUCCESS'
export const USER_DATA_ERROR='USER_DATA_ERROR'

export const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR='UPDATE_USER_ERROR'

export const UPDATE_QR_BINDING_SUCCESS='UPDATE_QR_BINDING_SUCCESS'
export const UPDATE_QR_BINDING_ERROR='UPDATE_QR_BINDING_ERROR'