export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS'
export const USER_LIST_ERROR = 'USER_LIST_ERROR'
export const USER_LIST_LOADING = 'USER_LOADING'

export const UPDATE_USERS_STATE_SUCCESS = 'UPDATE_USERS_STATE_SUCCESS'
export const UPDATE_USERS_STATE_ERROR = 'UPDATE_USERS_STATE_ERROR'
export const UPDATE_USERS_STATE_LOADING = 'UPDATE_USERS_STATE_LOADING'
